46-text-scaling
hpi-swa-teaching/MensaWidget pull request #51
Opened 2024-06-10 00:17 UTC by OscarUlb

Please test the graphical behavior.

2024-06-10 08:01 UTC, Kangaroo6942 commented on src/MensaWidget/MWFrame.class.st
> +	^ 460 @ (555 +( 25 * RealEstateAgent scaleFactor))
the space should be after the bracket

2024-06-10 08:04 UTC, Kangaroo6942 reviewed
The displaying works well when applied after setting a scale factor. Do you maybe see a way to get it to work, that the Widget adapts to a scale factor while it's openend? I don't thnik that really is a requirement or a real use case, but would be clean.
Also, do you see a way to test the rescaling or adaption to scaling?

2024-06-14 13:39 UTC, OscarUlb commented
Please ensure that when testing, you only change the scaling of the open widget between 175%-300% or 75%-125%. If you do not follow this, you will encounter the bug. To temporarily fix this, you need to close and reopen the widget.

2024-06-15 10:27 UTC, lchristus requested changes
All very nice but the test need to be reworked. They are not really testing anything right now, since the way they are written is correslating to our architecture

2024-06-15 10:27 UTC, lchristus commented on src/MensaWidget/MWFrame.class.st
> +	^ scrollBar
line break

2024-06-15 10:27 UTC, lchristus commented on src/MensaWidget/MWFrame.class.st
>  	super initialize.
line break

2024-06-15 10:27 UTC, lchristus commented on src/MensaWidget/MWFrame.class.st
> +	scrollBar := anObject
line break

2024-06-15 10:27 UTC, lchristus commented on src/MensaWidget/MWMeal.class.st
> +	^ 50 px
line break

2024-06-15 10:27 UTC, lchristus commented on src/MensaWidget/MWFrameTest.class.st
> +	widgetFrame := ((MWFrame new) scrollBar)
no brackets needed

2024-06-15 10:28 UTC, lchristus commented
We need to talk about that with @Kangaroo6942 maybe we do a extra ticket and merge after these changes have been implemented

2024-06-15 12:16 UTC, OscarUlb commented
> All very nice but the test need to be reworked. They are not really testing anything right now, since the way they are written is correslating to our architecture

Unfortunately, I don’t quite understand what you mean. The tests require the window. Before my changes, it was an instance of the class MWFrame. Now it is the window in which we open the Morphs. Functionally, there should be no difference, and all tests are green on my Image.

Could you please explain again what exactly you mean?

2024-06-15 17:03 UTC, Kangaroo6942 commented on src/MensaWidget/MWFrame.class.st
> +		vResizing: #spaceFill.
I think it would be nice to have an extra method that returns the alignment morph with the desired properties

2024-06-15 17:07 UTC, Kangaroo6942 reviewed
Looks good to me! Did you remove empty categories in the MWFrame class, because in my image they are still existent, but we had that problem before. Also - and I know this is not really the scope of this ticket - if the image is really small the testSize-test fails, which is not good for a testcase if it's dependent on something the user can change.

2024-06-15 17:07 UTC, Kangaroo6942 commented on src/MensaWidget/MWFrame.class.st
> +	self window: ((self buildFrameContent) openInWindowLabeled: 'Mensa Widget')
the inner brackets are not needed

2024-06-15 17:07 UTC, Kangaroo6942 commented on src/MensaWidget/MWFrame.class.st
> +		vResizing: #spaceFill.
I think it would be nice to have an extra method that returns the alignment morph with the desired properties

2024-06-15 18:03 UTC, Kangaroo6942 commented on src/MensaWidget/MWFrameTest.class.st
> +	self assert: self widgetFrame extent = ((MWFrame contentExtent)  + (10@30))
`(MWFrame contentExtent + (10 @ 30))`

2024-06-15 20:28 UTC, Kangaroo6942 approved these changes
all resolved

2024-06-17 06:42 UTC, Kangaroo6942 approved these changes
Looks good! Thanks for fixing this!

2024-06-17 08:19 UTC, lchristus approved these changes
all good

2024-06-17 08:35 UTC, merged