42 display eurosign
hpi-swa-teaching/MensaWidget pull request #56
Opened 2024-06-11 17:01 UTC by Kangaroo6942

added the ability to add a font with eurosign. Strangely all unknown characters default to the eurosign

2024-06-11 18:11 UTC, lchristus requested changes
very nice just slight mistake. Also is it possible to install the font by default?

2024-06-11 18:41 UTC, Kangaroo6942 commented
Since it is currently a problem that all special characters default to the Eurosign I wouldn't want to install it per default.
I also looked for a possibility to add the font when installing the widget, there probably is a possibiliy to provide a script for installation but I see that more as a concern of the initial setup/settings ticket.
If that feature is still desired, I have to go ask the teaching chair tomorrow.

2024-06-11 18:57 UTC, Kangaroo6942 commented on src/MensaWidget/MWFontLoader.class.st
done

2024-06-11 18:57 UTC, Kangaroo6942 commented on src/MensaWidget/MWFontLoader.class.st
> +	TextStyle installDefaultFallbackTextStyle
done

2024-06-11 19:02 UTC, lchristus approved these changes
i would talk to the client how these issues should be handled

2024-06-13 08:02 UTC, NilsKasper reviewed
seems good

2024-06-18 23:22 UTC, lchristus commented
This is not a requirement anymore therefor this will be closed

2024-06-18 23:22 UTC, closed without merging