unified spaces arround brackets
hpi-swa-teaching/MensaWidget pull request #65
Opened 2024-06-18 19:52 UTC by NilsKasper

unified spaces arround brackets

2024-06-18 23:19 UTC, lchristus requested changes
Very nice I guess I should have clarfied further we dont need a space when having a following semicolon but otherwise perfect

2024-06-18 23:19 UTC, lchristus commented on src/MensaWidget/MWMenuBar.class.st
> +	self date: (self date addDays: 1) ;
we dont need the space here

2024-06-18 23:19 UTC, lchristus commented on src/MensaWidget/MWFrame.class.st
> +			yourself) ;
no space here

2024-06-18 23:19 UTC, lchristus commented on src/MensaWidget/MWMenuBar.class.st
> +		setVertices: {0 @ 0. 0 @ 20. 20 @ 10} ;
no space here

2024-06-18 23:19 UTC, lchristus commented on src/MensaWidget/MWMenuBar.class.st
> +	self date: (self date addDays: -1) ;
no space here

2024-06-19 07:00 UTC, Kangaroo6942 approved these changes
Looks good, I found no unfixed methods that aren't going to be fixed on another branch

2024-06-22 10:47 UTC, lchristus approved these changes

2024-06-23 15:53 UTC, Kangaroo6942 approved these changes

2024-06-23 15:59 UTC, tommccaughey approved these changes

2024-06-23 16:00 UTC, lchristus approved these changes

2024-06-23 16:00 UTC, merged