80 refactor cleaner parser
hpi-swa-teaching/MensaWidget pull request #85
Opened 2024-07-10 19:38 UTC by Kangaroo6942

2024-07-10 20:41 UTC, OscarUlb approved these changes
Looks good I like the new names. Thank you!

2024-07-11 11:36 UTC, lchristus requested changes
I haven't had the chance yet to look at it in Squeak but looking at the changes in here it looks very nice. Just two things that you could have done on top.

2024-07-11 11:36 UTC, lchristus commented on src/MensaWidget/MWDataGettingWrapper.class.st
we have here a instance variable that is canteenDict which is not in the class documentation but also has no accessors so I assume it is not used and can be removed

2024-07-11 11:36 UTC, lchristus commented on src/MensaWidget/MWDataGettingWrapper.class.st
in get meals on date the constructor uses a lot of vars we can think if we do a line break there (sorry this was before already so can't comment on the line)

2024-07-11 13:40 UTC, Kangaroo6942 commented on src/MensaWidget/MWDataGettingWrapper.class.st
But canteenDict is a varibale that is in the scope of the MWDataGettingWrapper class, is it not?

2024-07-11 13:40 UTC, Kangaroo6942 commented on src/MensaWidget/MWDataGettingWrapper.class.st
same here

2024-07-11 15:16 UTC, lchristus commented on src/MensaWidget/MWDataGettingWrapper.class.st
what you mean by same as above I don't see them correlating

2024-07-11 16:16 UTC, Kangaroo6942 commented on src/MensaWidget/MWDataGettingWrapper.class.st
In my version of the code, there is not... Also, this variable exists in the DataGettingWrapper which's method is not the scope of this ticket

2024-07-11 16:17 UTC, Kangaroo6942 commented on src/MensaWidget/MWDataGettingWrapper.class.st
i referred to the scope of the ticket, again you described something that is in the DataGettingWrapper class

2024-07-11 16:18 UTC, Kangaroo6942 commented on src/MensaWidget/MWDataGettingWrapper.class.st
I mean, I can change it here, if that is desired

2024-07-11 16:56 UTC, lchristus approved these changes
I honestly did not realize that the changes i requested was only in files that are not your responsibility

2024-07-11 16:57 UTC, Kangaroo6942 commented
i think that would be part of Oscars ticket then

2024-07-11 16:58 UTC, lchristus commented
> i think that would be part of @OscarUlb ticket then

Yes I requested the same changes at Oscars branch aswell

2024-07-12 08:59 UTC, lchristus approved these changes
this is so perfect

2024-07-12 08:59 UTC, OscarUlb approved these changes

2024-07-12 08:59 UTC, merged